[colors.bright]
black = "{color8}"
blue = "{color1}"
cyan = "{color3}"
green = "{color5}"
magenta = "{color6}"
red = "{color4}"
white = "{color7}"
yellow = "{color2}"

[colors.cursor]
cursor = "#dfd5c0"
text = "CellForeground"

[colors.normal]
black = "{color0}"
blue = "{color1}"
cyan = "{color3}"
green = "{color5}"
magenta = "{color6}"
red = "{color4}"
white = "{color7}"
yellow = "{color2}"

[colors.primary]
background = "{color0}"
foreground = "{color7}"

[window.padding]
x = 20
y = 20
